In [2]:
import numpy as np

In [3]:
import pandas as pd 

In [6]:
df=pd.read_csv("Debernardi et al 2020 data.csv")

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 590 entries, 0 to 589
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   sample_id                590 non-null    object 
 1   patient_cohort           590 non-null    object 
 2   sample_origin            590 non-null    object 
 3   age                      590 non-null    int64  
 4   sex                      590 non-null    object 
 5   diagnosis                590 non-null    int64  
 6   stage                    199 non-null    object 
 7   benign_sample_diagnosis  208 non-null    object 
 8   plasma_CA19_9            350 non-null    float64
 9   creatinine               590 non-null    float64
 10  LYVE1                    590 non-null    float64
 11  REG1B                    590 non-null    float64
 12  TFF1                     590 non-null    float64
 13  REG1A                    306 non-null    float64
dtypes: float64(6), int64(2), o

In [8]:
df.patient_cohort.value_counts()

patient_cohort
Cohort1    332
Cohort2    258
Name: count, dtype: int64

In [9]:
df

sample_id patient_cohort sample_origin  age sex  diagnosis stage  \
0          S1        Cohort1          BPTB   33   F          1   NaN   
1         S10        Cohort1          BPTB   81   F          1   NaN   
2        S100        Cohort2          BPTB   51   M          1   NaN   
3        S101        Cohort2          BPTB   61   M          1   NaN   
4        S102        Cohort2          BPTB   62   M          1   NaN   
..        ...            ...           ...  ...  ..        ...   ...   
585      S549        Cohort2          BPTB   68   M          3    IV   
586      S558        Cohort2          BPTB   71   F          3    IV   
587      S560        Cohort2          BPTB   63   M          3    IV   
588      S583        Cohort2          BPTB   75   F          3    IV   
589      S590        Cohort1          BPTB   74   M          3    IV   

    benign_sample_diagnosis  plasma_CA19_9  creatinine     LYVE1       REG1B  \
0                       NaN           11.7     1.83222  0.893219   52.948840   
1                       NaN            NaN     0.97266  2.037585   94.467030   
2                       NaN            7.0     0.78039  0.145589  102.366000   
3                       NaN            8.0     0.70122  0.002805   60.579000   
4                       NaN            9.0     0.21489  0.000860   65.540000   
..                      ...            ...         ...       ...         ...   
585                     NaN            NaN     0.52026  7.058209  156.241000   
586                     NaN            NaN     0.85956  8.341207   16.915000   
587                     NaN            NaN     1.36851  7.674707  289.701000   
588                     NaN            NaN     1.33458  8.206777  205.930000   
589                     NaN         1488.0     1.50423  8.200958  411.938275   

            TFF1      REG1A  
0     654.282174   1262.000  
1     209.488250    228.407  
2     461.141000        NaN  
3     142.950000        NaN  
4      41.088000        NaN  
..           ...        ...  
585   525.178000        NaN  
586   245.947000        NaN  
587   537.286000        NaN  
588   722.523000        NaN  
589  2021.321078  13200.000  

[590 rows x 14 columns]

In [10]:
df.sample_origin.value_counts()

sample_origin
BPTB    409
LIV     132
ESP      29
UCL      20
Name: count, dtype: int64

In [11]:
df.drop(columns=["sample_id"],inplace=True)

In [13]:
!pip install scikit-learn

In [14]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [16]:
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')

In [17]:
l=list(df.columns)
l.insert(0,'patient_cohort')
x_1=pd.DataFrame(ct.fit_transform(df),columns=l)

In [18]:
x_1

patient_cohort patient_cohort sample_origin age sex diagnosis stage  \
0              1.0            0.0          BPTB  33   F         1   NaN   
1              1.0            0.0          BPTB  81   F         1   NaN   
2              0.0            1.0          BPTB  51   M         1   NaN   
3              0.0            1.0          BPTB  61   M         1   NaN   
4              0.0            1.0          BPTB  62   M         1   NaN   
..             ...            ...           ...  ..  ..       ...   ...   
585            0.0            1.0          BPTB  68   M         3    IV   
586            0.0            1.0          BPTB  71   F         3    IV   
587            0.0            1.0          BPTB  63   M         3    IV   
588            0.0            1.0          BPTB  75   F         3    IV   
589            1.0            0.0          BPTB  74   M         3    IV   

    benign_sample_diagnosis plasma_CA19_9 creatinine     LYVE1       REG1B  \
0                       NaN          11.7    1.83222  0.893219    52.94884   
1                       NaN           NaN    0.97266  2.037585    94.46703   
2                       NaN           7.0    0.78039  0.145589     102.366   
3                       NaN           8.0    0.70122  0.002805      60.579   
4                       NaN           9.0    0.21489   0.00086       65.54   
..                      ...           ...        ...       ...         ...   
585                     NaN           NaN    0.52026  7.058209     156.241   
586                     NaN           NaN    0.85956  8.341207      16.915   
587                     NaN           NaN    1.36851  7.674707     289.701   
588                     NaN           NaN    1.33458  8.206777      205.93   
589                     NaN        1488.0    1.50423  8.200958  411.938275   

            TFF1    REG1A  
0     654.282174   1262.0  
1      209.48825  228.407  
2        461.141      NaN  
3         142.95      NaN  
4         41.088      NaN  
..           ...      ...  
585      525.178      NaN  
586      245.947      NaN  
587      537.286      NaN  
588      722.523      NaN  
589  2021.321078  13200.0  

[590 rows x 14 columns]

In [19]:
x_1.sample_origin.value_counts()

sample_origin
BPTB    409
LIV     132
ESP      29
UCL      20
Name: count, dtype: int64

In [20]:
x_1.stage.isna().value_counts()

stage
True     391
False    199
Name: count, dtype: int64

In [21]:
x_1.benign_sample_diagnosis.value_counts()

benign_sample_diagnosis
Pancreatitis                                                    41
Pancreatitis (Chronic)                                          35
Gallstones                                                      21
Pancreatitis (Alcohol-Chronic)                                  11
Cholecystitis                                                    9
Serous cystadenoma - NOS                                         7
Choledocholiathiasis                                             6
Abdominal Pain                                                   6
Pancreatitis (Idiopathic)                                        4
Pancreatitis (Alcohol-Chronic-Pseuodcyst)                        4
Pancreatitis (Gallstone)                                         4
Pancreatitis (Pseudocyst)                                        4
Premalignant lesions-Mucinous cystadenoma-NOS                    3
Pancreatitis (Autoimmune)                                        3
Serous microcystic adenoma            

In [22]:
from sklearn.impute import SimpleImputer
si=SimpleImputer(strategy='constant',fill_value='0')
a=si.fit_transform(x_1[["stage"]])
l=[]
for i in range(len(a)):
    l.append(a[i][0])
x_1["stage"]=l    

In [23]:
x_1["stage"]

0       0
1       0
2       0
3       0
4       0
       ..
585    IV
586    IV
587    IV
588    IV
589    IV
Name: stage, Length: 590, dtype: object

In [24]:
si_1=SimpleImputer(strategy='constant',fill_value='0')
a=si_1.fit_transform(x_1[["benign_sample_diagnosis"]])
l=[]
for i in range(len(a)):
    l.append(a[i][0])
x_1["benign_sample_diagnosis"]=l

In [25]:
si_2=SimpleImputer(strategy='constant',fill_value=0)
a=si_2.fit_transform(x_1[["REG1A"]])
l=[]
for i in range(len(a)):
    l.append(a[i][0])
x_1["REG1A"]=l    

In [26]:
x_1.plasma_CA19_9.isna().value_counts()

plasma_CA19_9
False    350
True     240
Name: count, dtype: int64

In [27]:
si_3=SimpleImputer(strategy='constant',fill_value=0)
a=si_3.fit_transform(x_1[["plasma_CA19_9"]])
l=[]
for i in range(len(a)):
    l.append(a[i][0])
x_1["plasma_CA19_9"]=l  

In [30]:
x_1.stage.value_counts()

stage
0      391
III     76
IIB     68
IV      21
IB      12
IIA     11
II       7
IA       3
I        1
Name: count, dtype: int64

In [28]:
x_1["plasma_CA19_9"]

0        11.7
1         0.0
2         7.0
3         8.0
4         9.0
        ...  
585       0.0
586       0.0
587       0.0
588       0.0
589    1488.0
Name: plasma_CA19_9, Length: 590, dtype: float64

In [29]:
x_1.TFF1.isna().value_counts()

TFF1
False    590
Name: count, dtype: int64

In [31]:
order_stage=["0","IA","IB","I","IIA","IIB","II","III","IV"]

In [32]:
x_1["stage"]

0       0
1       0
2       0
3       0
4       0
       ..
585    IV
586    IV
587    IV
588    IV
589    IV
Name: stage, Length: 590, dtype: object

In [33]:
from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder(categories=[order_stage])
x_1["stage"]=oe.fit_transform(x_1[["stage"]])

In [34]:
x_1["stage"].value_counts()

stage
0.0    391
7.0     76
5.0     68
8.0     21
2.0     12
4.0     11
6.0      7
1.0      3
3.0      1
Name: count, dtype: int64

In [35]:
x_1

patient_cohort patient_cohort sample_origin age sex diagnosis  stage  \
0              1.0            0.0          BPTB  33   F         1    0.0   
1              1.0            0.0          BPTB  81   F         1    0.0   
2              0.0            1.0          BPTB  51   M         1    0.0   
3              0.0            1.0          BPTB  61   M         1    0.0   
4              0.0            1.0          BPTB  62   M         1    0.0   
..             ...            ...           ...  ..  ..       ...    ...   
585            0.0            1.0          BPTB  68   M         3    8.0   
586            0.0            1.0          BPTB  71   F         3    8.0   
587            0.0            1.0          BPTB  63   M         3    8.0   
588            0.0            1.0          BPTB  75   F         3    8.0   
589            1.0            0.0          BPTB  74   M         3    8.0   

    benign_sample_diagnosis  plasma_CA19_9 creatinine     LYVE1       REG1B  \
0                         0           11.7    1.83222  0.893219    52.94884   
1                         0            0.0    0.97266  2.037585    94.46703   
2                         0            7.0    0.78039  0.145589     102.366   
3                         0            8.0    0.70122  0.002805      60.579   
4                         0            9.0    0.21489   0.00086       65.54   
..                      ...            ...        ...       ...         ...   
585                       0            0.0    0.52026  7.058209     156.241   
586                       0            0.0    0.85956  8.341207      16.915   
587                       0            0.0    1.36851  7.674707     289.701   
588                       0            0.0    1.33458  8.206777      205.93   
589                       0         1488.0    1.50423  8.200958  411.938275   

            TFF1      REG1A  
0     654.282174   1262.000  
1      209.48825    228.407  
2        461.141      0.000  
3         142.95      0.000  
4         41.088      0.000  
..           ...        ...  
585      525.178      0.000  
586      245.947      0.000  
587      537.286      0.000  
588      722.523      0.000  
589  2021.321078  13200.000  

[590 rows x 14 columns]

In [36]:
x_1.benign_sample_diagnosis.value_counts()

benign_sample_diagnosis
0                                                               382
Pancreatitis                                                     41
Pancreatitis (Chronic)                                           35
Gallstones                                                       21
Pancreatitis (Alcohol-Chronic)                                   11
Cholecystitis                                                     9
Serous cystadenoma - NOS                                          7
Abdominal Pain                                                    6
Choledocholiathiasis                                              6
Pancreatitis (Alcohol-Chronic-Pseuodcyst)                         4
Pancreatitis (Gallstone)                                          4
Pancreatitis (Pseudocyst)                                         4
Pancreatitis (Idiopathic)                                         4
Pancreatitis (Autoimmune)                                         3
Serous microcystic adeno

In [37]:
for i in range(len(x_1["benign_sample_diagnosis"])):
    if (x_1["benign_sample_diagnosis"][i]=='0'):
        x_1["benign_sample_diagnosis"][i]=0
    else:
        x_1["benign_sample_diagnosis"][i]=1

C:\Users\STUDENT\AppData\Local\Temp\ipykernel_12188\1584284203.py:3: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  x_1["benign_sample_diagnosis"][i]=0
C:\Users\STUDENT\AppData\Local\Temp\ipykernel_12188\1584284203.py:3: SettingWithCopyWarnin

In [38]:
x_1

patient_cohort patient_cohort sample_origin age sex diagnosis  stage  \
0              1.0            0.0          BPTB  33   F         1    0.0   
1              1.0            0.0          BPTB  81   F         1    0.0   
2              0.0            1.0          BPTB  51   M         1    0.0   
3              0.0            1.0          BPTB  61   M         1    0.0   
4              0.0            1.0          BPTB  62   M         1    0.0   
..             ...            ...           ...  ..  ..       ...    ...   
585            0.0            1.0          BPTB  68   M         3    8.0   
586            0.0            1.0          BPTB  71   F         3    8.0   
587            0.0            1.0          BPTB  63   M         3    8.0   
588            0.0            1.0          BPTB  75   F         3    8.0   
589            1.0            0.0          BPTB  74   M         3    8.0   

    benign_sample_diagnosis  plasma_CA19_9 creatinine     LYVE1       REG1B  \
0                         0           11.7    1.83222  0.893219    52.94884   
1                         0            0.0    0.97266  2.037585    94.46703   
2                         0            7.0    0.78039  0.145589     102.366   
3                         0            8.0    0.70122  0.002805      60.579   
4                         0            9.0    0.21489   0.00086       65.54   
..                      ...            ...        ...       ...         ...   
585                       0            0.0    0.52026  7.058209     156.241   
586                       0            0.0    0.85956  8.341207      16.915   
587                       0            0.0    1.36851  7.674707     289.701   
588                       0            0.0    1.33458  8.206777      205.93   
589                       0         1488.0    1.50423  8.200958  411.938275   

            TFF1      REG1A  
0     654.282174   1262.000  
1      209.48825    228.407  
2        461.141      0.000  
3         142.95      0.000  
4         41.088      0.000  
..           ...        ...  
585      525.178      0.000  
586      245.947      0.000  
587      537.286      0.000  
588      722.523      0.000  
589  2021.321078  13200.000  

[590 rows x 14 columns]

In [39]:
ct_1=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[2,4])],remainder='passthrough')
x_2=pd.DataFrame(ct_1.fit_transform(x_1))
x_2

0    1    2    3    4    5    6    7   8  9    10 11      12       13  \
0    1.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  33  1  0.0  0    11.7  1.83222   
1    1.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  81  1  0.0  0     0.0  0.97266   
2    1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  51  1  0.0  0     7.0  0.78039   
3    1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  61  1  0.0  0     8.0  0.70122   
4    1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  62  1  0.0  0     9.0  0.21489   
..   ...  ...  ...  ...  ...  ...  ...  ...  .. ..  ... ..     ...      ...   
585  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  68  3  8.0  0     0.0  0.52026   
586  1.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  71  3  8.0  0     0.0  0.85956   
587  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  63  3  8.0  0     0.0  1.36851   
588  1.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  75  3  8.0  0     0.0  1.33458   
589  1.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  74  3  8.0  0  1488.0  1.50423   

           14          15           16       17  
0    0.893219    52.94884   654.282174   1262.0  
1    2.037585    94.46703    209.48825  228.407  
2    0.145589     102.366      461.141      0.0  
3    0.002805      60.579       142.95      0.0  
4     0.00086       65.54       41.088      0.0  
..        ...         ...          ...      ...  
585  7.058209     156.241      525.178      0.0  
586  8.341207      16.915      245.947      0.0  
587  7.674707     289.701      537.286      0.0  
588  8.206777      205.93      722.523      0.0  
589  8.200958  411.938275  2021.321078  13200.0  

[590 rows x 18 columns]

In [40]:
x=x_2
y=x_2[9]
x_2.drop(columns=[9],inplace=True)

In [41]:
x=x.astype(float)
y=y.astype(float)

In [42]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=34,test_size=0.15)

In [43]:
len(x_train),len(x_test)

(501, 89)

In [44]:
x_train_1=np.array(x_train)
y_train_1=np.array(y_train)
x_train_1

array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        5.35400000e+00, 4.33430000e+01, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, ...,
        2.19129024e+02, 4.14613900e+02, 0.00000000e+00],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, ...,
        2.79524840e+02, 9.77809600e+02, 0.00000000e+00],
       ...,
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        1.13094000e+02, 1.25671200e+03, 0.00000000e+00],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        2.83325400e+01, 1.13776998e+02, 8.41230000e+01],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, ...,
        1.44475310e+02, 1.80301468e+03, 3.84086000e+02]])

In [45]:
x_test.dtypes

0     float64
1     float64
2     float64
3     float64
4     float64
5     float64
6     float64
7     float64
8     float64
10    float64
11    float64
12    float64
13    float64
14    float64
15    float64
16    float64
17    float64
dtype: object

In [46]:
x_test.dtypes

0     float64
1     float64
2     float64
3     float64
4     float64
5     float64
6     float64
7     float64
8     float64
10    float64
11    float64
12    float64
13    float64
14    float64
15    float64
16    float64
17    float64
dtype: object

In [48]:
pip install lightgbm

   ---------------------------------------- 0.0/1.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/1.3 MB ? eta -:--:--
    --------------------------------------- 0.0/1.3 MB 262.6 kB/s eta 0:00:05
    --------------------------------------- 0.0/1.3 MB 262.6 kB/s eta 0:00:05
   - -------------------------------------- 0.0/1.3 MB 217.9 kB/s eta 0:00:06
   - -------------------------------------- 0.1/1.3 MB 272.3 kB/s eta 0:00:05
   -- ------------------------------------- 0.1/1.3 MB 245.8 kB/s eta 0:00:06
   -- ------------------------------------- 0.1/1.3 MB 290.5 kB/s eta 0:00:05
   --- ------------------------------------ 0.1/1.3 MB 297.7 kB/s eta 0:00:05
   --- ------------------------------------ 0.1/1.3 MB 288.1 kB/s eta 0:00:05
   ---- ----------------------------------- 0.1/1.3 MB 303.9 kB/s eta 0:00:04
   ---- ----------------------------------- 0.2/1.3 MB 295.6 kB/s eta 0:00:05
   ----- ----

In [49]:
import lightgbm as lgb

In [50]:
lc=lgb.LGBMClassifier()
lc.fit(x_train,y_train)

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000098 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 872
[LightGBM] [Info] Number of data points in the train set: 501, number of used features: 16
[LightGBM] [Info] Start training from score -1.205971
[LightGBM] [Info] Start training from score -1.029220
[LightGBM] [Info] Start training from score -1.069112
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits

LGBMClassifier()

In [51]:
x_test

0    1    2    3    4    5    6    7     8    10   11     12        13  \
161  1.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  61.0  0.0  0.0    0.0  1.176240   
283  0.0  0.0  1.0  0.0  0.0  1.0  1.0  0.0  66.0  0.0  1.0   86.0  1.877460   
296  1.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  46.0  0.0  1.0  114.8  1.402440   
497  0.0  0.0  1.0  0.0  1.0  0.0  1.0  0.0  72.0  7.0  0.0  655.0  0.327990   
7    1.0  0.0  0.0  0.0  1.0  0.0  0.0  1.0  58.0  0.0  0.0   11.0  0.893490   
..   ...  ...  ...  ...  ...  ...  ...  ...   ...  ...  ...    ...       ...   
131  1.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  56.0  0.0  0.0    0.0  1.391130   
152  1.0  0.0  0.0  0.0  1.0  0.0  1.0  0.0  58.0  0.0  0.0    0.0  1.198860   
308  1.0  0.0  0.0  0.0  0.0  1.0  1.0  0.0  41.0  0.0  1.0   14.0  2.326467   
159  1.0  0.0  0.0  0.0  0.0  1.0  0.0  1.0  43.0  0.0  0.0    0.0  0.972660   
572  0.0  1.0  0.0  0.0  0.0  1.0  1.0  0.0  78.0  8.0  0.0    0.0  0.667290   

           14          15           16       17  
161  1.632705   52.800240   267.694524  158.063  
283  5.224256   48.348643  1202.169600  127.562  
296  1.669079   11.545359   586.871800  137.000  
497  9.044431  215.752320   620.140350  464.054  
7    0.003574    3.730000    40.294000    0.000  
..        ...         ...          ...      ...  
131  2.984651   48.119630   269.088550  145.198  
152  3.043465   37.135014   167.871849  114.798  
308  7.550356   27.431467   581.187009  221.438  
159  0.406951   35.689000   254.224000    0.000  
572  6.882451  109.417560   197.893900    0.000  

[89 rows x 17 columns]

In [52]:
y_pred=lc.predict(x_test)
y_pred

array([1., 2., 2., 3., 1., 1., 1., 2., 1., 2., 3., 2., 1., 1., 3., 3., 2.,
       2., 1., 3., 3., 1., 1., 3., 1., 3., 2., 3., 3., 3., 3., 1., 1., 2.,
       2., 2., 1., 2., 2., 3., 2., 2., 2., 3., 1., 2., 2., 1., 1., 2., 2.,
       2., 3., 1., 1., 2., 2., 3., 3., 3., 1., 1., 2., 3., 1., 1., 3., 2.,
       1., 3., 3., 2., 1., 3., 1., 1., 3., 2., 3., 3., 2., 1., 1., 1., 1.,
       1., 2., 1., 3.])

In [53]:
from sklearn.metrics import accuracy_score,confusion_matrix,balanced_accuracy_score
cm=confusion_matrix(y_pred,y_test)
print(cm)
accuracy_score(y_pred,y_test)*100

[[33  0  0]
 [ 0 29  0]
 [ 0  0 27]]


100.0

In [54]:
balanced_accuracy_score(y_pred,y_test)*100

100.0